### PR TITLE
chore(deps): lock file maintenance

### PR DESCRIPTION
**Pull request by pleo-bot-renovate**
This PR contains the following updates:

| Update | Change |
|---|---|
| lockFileMaintenance | All locks refreshed |

🔧 This Pull Request updates lock files to use the latest dependency versions.

---

### Configuration

📅 **Schedule**: Branch creation - "every weekday" in timezone CET, Automerge - "after 8am and before 5pm every weekday" in timezone CET.

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by VictorPascualV** [comment]
@r0binary is there an opportunity for us here to let our Renovate setup take care of these kind of PRs automatically?

**Review by VictorPascualV — APPROVED** [review]

**Comment by r0binary** [comment]
> @r0binary is there an opportunity for us here to let our Renovate setup take care of these kind of PRs automatically?

Yes, we'd need to get an extra machine account token for each public repo so in case of a breach nobody can access pleo internals with the tokens. Might be ok though if all public repos shared the same token. WDYT @marcos-arranz ?

**Review by r0binary — APPROVED** [review]

**Comment by marcos-arranz** [comment]
> > @r0binary is there an opportunity for us here to let our Renovate setup take care of these kind of PRs automatically?
> 
> Yes, we'd need to get an extra machine account token for each public repo so in case of a breach nobody can access pleo internals with the tokens. Might be ok though if all public repos shared the same token. WDYT @marcos-arranz ?

It'd be better to make the automerge based on branch. The reason is that only fine-grained tokens can be scoped to one or a few repositories, but fine-grained have a maximum expiration date of a year. It could be something we live with, but if possible I'd try to avoid it completely

**Comment by r0binary** [comment]
> > > @r0binary is there an opportunity for us here to let our Renovate setup take care of these kind of PRs automatically?
> > 
> > 
> > Yes, we'd need to get an extra machine account token for each public repo so in case of a breach nobody can access pleo internals with the tokens. Might be ok though if all public repos shared the same token. WDYT @marcos-arranz ?
> 
> It'd be better to make the automerge based on branch. The reason is that only fine-grained tokens can be scoped to one or a few repositories, but fine-grained have a maximum expiration date of a year. It could be something we live with, but if possible I'd try to avoid it completely

Maybe this goes too much into the details here. Do we have ticket for that in Linear? I'd love to have one and read about the details of the automerge based on branch solution you mentioned.

**Comment by marcos-arranz** [comment]
@r0binary Created here https://linear.app/pleo/issue/DEVX-1851/set-up-auto-merge-for-public-repos

**Pull request merged**
