### PR TITLE
Ensure the application container image is released on the 'pleo-io' container registry

### PR DESCRIPTION
**Pull request by andersfischernielsen**
This PR is tagged as `patch` in order to trigger the release workflow and release a container image on `pleo-io`. While this only changes the CODEOWNERS to reflect the which team is maintaining the repository and therefore doesn't follow semantic versioning, it does allow us to deploy the app to the `pleo-io` container registry, which in turn allows deploying the container image from `pleo-io`.

### CODE REVIEW

**Comment by jsfr** [comment]
I'm not sure if I get this PR and what it says it does, the ticket it's linked to and the actual changes.

**Comment by andersfischernielsen** [comment]
> I'm not sure if I get this PR and what it says it does, the ticket it's linked to and the actual changes.

@jsfr Should I add more details to the description? 🤔 Wanna make sure we understand why it's set up this way 😄

**Comment by jsfr** [comment]
My confusion stems from the fact that:

The title is: `Transfer repository to 'pleo-io'`
The ticket is named: `Ensure terraform pulls the correct container image for file-distributor`
The description talks about Codeowners file and the only change in the files is to the Codeowners file.

So maybe another question: What is the intent of this PR?

**Comment by andersfischernielsen** [comment]
> My confusion stems from the fact that:
> 
> The title is: `Transfer repository to 'pleo-io'` The ticket is named: `Ensure terraform pulls the correct container image for file-distributor` The description talks about Codeowners file and the only change in the files is to the Codeowners file.
> 
> So maybe another question: What is the intent of this PR?

@jsfr Updated both title and description to try to make it clear what we want to accomplish. LMK WYT!

**Comment by jsfr** [comment]
I think there might be an issue with the name of the team

image

**Comment by andersfischernielsen** [comment]
> I think there might be an issue with the name of the team
> 
> image

@jsfr Fixed, the access permission settings weren't configured as expected.

**Review by jsfr — APPROVED** [review]

**Pull request merged**
